### ISSUE TITLE
It dont locates level.dat

### ISSUE THREAD

**Issue by fhavio** [mide/minecraft-overviewer#28] opened 2019-02-04 23:58 UTC
Hello,

I have install this overviewer version by your docker everything went fine until i run your command to render.

I'm running like this

docker run \
  --rm -it marctv/overviewer113\
  -v [world-directory]:/tmp/world/:ro \
  -v [config.py-directory]/config.py:/tmp/config/config.py:ro \
  -v [render-directory]:/tmp/export/:rw

in return i get this
"No level.dat file in '/home/minecraft/server/world'. Are you sure you have the right path?"

I search for the tmp folder and they werent there, so i create them to force, but the error keeps.
Also copy the file config.py to the tmp folder and nothing.

Can you give me a proper command example maybe i'm making something wrong
Hope you can help

**Comment by mide** [comment] 2019-02-25 18:34
I'm not sure exactly what the problem is you're having, but it doesn't look like you're running this project. `marctv/overviewer113` is on GitHub at [github.com/mtoensing/Docker-Overviewer-1.13.X](https://github.com/mtoensing/Docker-Overviewer-1.13.X).

**Comment by mide** [comment] 2019-02-25 18:37
And it seems you already opened an issue there https://github.com/mtoensing/Docker-Overviewer-1.13.X/issues/2. I'm going to close this.

**Closed as completed by mide** 2019-02-25 18:37 UTC
Labels: invalid
